#!/usr/bin/env python3

# quick tool for converting the IPA strings generated by https://aryanpingle.com/Runic/ (or https://ipachart.app/ipa-translator) into strings where each character corresponds to a specific trunic rune,
# with the characters being ASCII, making them more easily able to be parsed and stuff in Odin

# change InputToStringSet.txt and then run this program. It should be in the following format:
"""
one
two
three
four
five
-
wən
tu
θɹi
fɔɹ
faɪv
"""
# this is so that it becomes easy to copy-paste all the input and output from https://aryanpingle.com/Runic/.
# Note that the dividing line has to be exactly "-", and also that each entry is seperated by a new line, meaning that an entry can't consist of multiple lines.



# this is what each phoneme gets converted to. Look at the table in https://tunic.wiki/books/secrets/page/trunic and compare it to the table below
# o U a G F e L B I
# V R Y E A Z i x W
# -----------------
# N H T S t w s r k
# p f g d n m z j v
# c   h M     y l b
def ConvertToTrunicString(ipa_input: str) -> str:
    output_string: str = ""

    ipa_input = ipa_input.replace("ˈ", "")  # pretty sure that this character (which isn't an apostrophe!) is irrelevant to trunic conversion
    ipa_input = ipa_input.replace("ː", "")  # pretty sure that this character (which isn't a colon!) is irrelevant to trunic conversion
    ipa_input = ipa_input.replace("ʌ", "ə")  # I think these are the same in trunic

    while ipa_input != "":

        # include these symbols directly into the output
        if ipa_input[0] in " .,!?-\"\':":
            output_string += ipa_input[0]
            ipa_input = ipa_input[1:]
            continue


        # do all the two-character runes first
        if len(ipa_input) >= 2:
            if ipa_input[:2] == "oʊ":
                ipa_input = ipa_input[2:]
                output_string += "o"
                continue
            if ipa_input[:2] == "eɪ":
                ipa_input = ipa_input[2:]
                output_string += "B"
                continue
            if ipa_input[:2] == "aɪ":
                ipa_input = ipa_input[2:]
                output_string += "I"
                continue
            if ipa_input[:2] == "ʊr" or ipa_input[:2] == "ɔɹ":
                ipa_input = ipa_input[2:]
                output_string += "R"
                continue
            if ipa_input[:2] == "ɪr" or ipa_input[:2] == "iɹ":
                ipa_input = ipa_input[2:]
                output_string += "Y"
                continue
            if ipa_input[:2] == "ɛr" or ipa_input[:2] == "ɛɹ":
                ipa_input = ipa_input[2:]
                output_string += "E"
                continue
            if ipa_input[:2] == "ɑr":
                ipa_input = ipa_input[2:]
                output_string += "A"
                continue
            if ipa_input[:2] == "ɔɪ":
                ipa_input = ipa_input[2:]
                output_string += "x"
                continue
            if ipa_input[:2] == "aʊ":
                ipa_input = ipa_input[2:]
                output_string += "W"
                continue
            if ipa_input[:2] == "dʒ":
                ipa_input = ipa_input[2:]
                output_string += "y"
                continue

        # do all the one-character runes
        if ipa_input[0] == "u":
            ipa_input = ipa_input[1:]
            output_string += "U"
            continue
        if ipa_input[0] == "æ":
            ipa_input = ipa_input[1:]
            output_string += "a"
            continue
        if ipa_input[0] == "ɑ" or ipa_input[0] == "ɔ":
            ipa_input = ipa_input[1:]
            output_string += "G"
            continue
        if ipa_input[0] == "i":
            ipa_input = ipa_input[1:]
            output_string += "F"
            continue
        if ipa_input[0] == "ɛ":
            ipa_input = ipa_input[1:]
            output_string += "e"
            continue
        if ipa_input[0] == "ʊ":
            ipa_input = ipa_input[1:]
            output_string += "L"
            continue
        if ipa_input[0] == "ɝ":
            ipa_input = ipa_input[1:]
            output_string += "V"
            continue
        if ipa_input[0] == "ə":
            ipa_input = ipa_input[1:]
            output_string += "Z"
            continue
        if ipa_input[0] == "ɪ":
            ipa_input = ipa_input[1:]
            output_string += "i"
            continue
        if ipa_input[0] == "ŋ":
            ipa_input = ipa_input[1:]
            output_string += "N"
            continue
        if ipa_input[0] == "ʒ":
            ipa_input = ipa_input[1:]
            output_string += "H"
            continue
        if ipa_input[0] == "θ":
            ipa_input = ipa_input[1:]
            output_string += "T"
            continue
        if ipa_input[0] == "ʃ":
            ipa_input = ipa_input[1:]
            output_string += "S"
            continue
        if ipa_input[0] == "t":
            ipa_input = ipa_input[1:]
            output_string += "t"
            continue
        if ipa_input[0] == "w":
            ipa_input = ipa_input[1:]
            output_string += "w"
            continue
        if ipa_input[0] == "s":
            ipa_input = ipa_input[1:]
            output_string += "s"
            continue
        if ipa_input[0] == "r" or ipa_input[0] == "ɹ":
            ipa_input = ipa_input[1:]
            output_string += "r"
            continue
        if ipa_input[0] == "k":
            ipa_input = ipa_input[1:]
            output_string += "k"
            continue
        if ipa_input[0] == "p":
            ipa_input = ipa_input[1:]
            output_string += "p"
            continue
        if ipa_input[0] == "f":
            ipa_input = ipa_input[1:]
            output_string += "f"
            continue
        if ipa_input[0] == "g" or ipa_input[0] == "ɡ":
            ipa_input = ipa_input[1:]
            output_string += "g"
            continue
        if ipa_input[0] == "d":
            ipa_input = ipa_input[1:]
            output_string += "d"
            continue
        if ipa_input[0] == "n":
            ipa_input = ipa_input[1:]
            output_string += "n"
            continue
        if ipa_input[0] == "m":
            ipa_input = ipa_input[1:]
            output_string += "m"
            continue
        if ipa_input[0] == "z":
            ipa_input = ipa_input[1:]
            output_string += "z"
            continue
        if ipa_input[0] == "j":
            ipa_input = ipa_input[1:]
            output_string += "j"
            continue
        if ipa_input[0] == "v":
            ipa_input = ipa_input[1:]
            output_string += "v"
            continue
        if ipa_input[0] == "ʧ":
            ipa_input = ipa_input[1:]
            output_string += "c"
            continue
        if ipa_input[0] == "h":
            ipa_input = ipa_input[1:]
            output_string += "h"
            continue
        if ipa_input[0] == "ð":
            ipa_input = ipa_input[1:]
            output_string += "M"
            continue
        if ipa_input[0] == "l" or ipa_input[0] == "ɫ":
            ipa_input = ipa_input[1:]
            output_string += "l"
            continue
        if ipa_input[0] == "b":
            ipa_input = ipa_input[1:]
            output_string += "b"
            continue

        print("no valid conversion was found for the start of this string:", ipa_input)
        exit()

    return output_string



def QuoteRepr(text: str) -> str:
    text = text.replace("\"", "\\\"")
    text = text.replace("\'", "\\\'")
    return text



# parse input file
with open("input_to_string_set.txt") as f:
    lines = f.readlines()

while lines[-1].strip() == "":
    del lines[-1]

normal_text: list = []
ipa_text: list = []
has_found_dividing_line: bool = False
line_number: int = 0
line_number_of_dividing_line: int = 0
for line in lines:
    line_number += 1
    if line.strip() == "-":
        has_found_dividing_line = True
        line_number_of_dividing_line = line_number
        continue
    if has_found_dividing_line:
        # check for incorrect translation
        if line[0] in " .,!?-\"\':" or line[-2] == " " or line.count("  ") > 0 or line.count(" .") > 0 or line.count(" ,") or line.count(" !") or line.count(" ?") or line.count(" \" ") or line.count(" \' ") or line.count("- ") or line.count(" -"):
            input(f"incorrect space placement found. Press enter if this is a false positive that can be ignored. Press Control+c if it is an error.\nMost likely caused by a word failing to be translated to IPA by the runic translator. Detected in the string \"{line[:-1]}\" on line {line_number} (pair of line {line_number - line_number_of_dividing_line})")
            
        ipa_text.append(line.strip())
    else:
        normal_text.append(line.strip())

if len(normal_text) != len(ipa_text):
    print(f"something is wrong with the input file. The amount of normal text lines ({len(normal_text)}) is not the same as the amount of IPA text lines ({len(ipa_text)}). Is the dividing line not made as a row with just a \'-\'?")
    exit()


# turn every item into the correct syntax for the odin arrays
for i in range(len(normal_text)):
    print("    {\"" + QuoteRepr(normal_text[i]) + "\", \"" + QuoteRepr(ConvertToTrunicString(ipa_text[i])) + "\"},")
