#!/usr/bin/env python3

# quick tool for converting the IPA strings generated by https://ipachart.app/ipa-translator into strings where each character corresponds to a specific trunic rune,
# with the characters being ASCII, making them more easily able to be parsed and stuff in Odin

# change the value of this string to change what the program outputs
ipa_input: str = "tɛst strɪŋ! ˈpiːnɪs ˈeɪnəs"



output_string: str = ""

ipa_input = ipa_input.replace("ˈ", "")  # pretty sure that this character (which isn't an apostrophe!) is irrelevant to trunic conversion
ipa_input = ipa_input.replace("ː", "")  # pretty sure that this character (which isn't a colon!) is irrelevant to trunic conversion
ipa_input = ipa_input.replace("ʌ", "ə")  # I think these are the same in trunic

while ipa_input != "":

    # include these symbols directly into the output
    if ipa_input[0] in " .,!?-\"\'":
        output_string += ipa_input[0]
        ipa_input = ipa_input[1:]
        continue


    # do all the two-character runes first
    if len(ipa_input) >= 2:
        if ipa_input[:2] == "oʊ":
            ipa_input = ipa_input[2:]
            output_string += "o"
            continue
        if ipa_input[:2] == "eɪ":
            ipa_input = ipa_input[2:]
            output_string += "B"
            continue
        if ipa_input[:2] == "aɪ":
            ipa_input = ipa_input[2:]
            output_string += "I"
            continue
        if ipa_input[:2] == "ʊr":
            ipa_input = ipa_input[2:]
            output_string += "R"
            continue
        if ipa_input[:2] == "ɪr":
            ipa_input = ipa_input[2:]
            output_string += "Y"
            continue
        if ipa_input[:2] == "ɛr":
            ipa_input = ipa_input[2:]
            output_string += "E"
            continue
        if ipa_input[:2] == "ɑr":
            ipa_input = ipa_input[2:]
            output_string += "A"
            continue
        if ipa_input[:2] == "ɔɪ":
            ipa_input = ipa_input[2:]
            output_string += "x"
            continue
        if ipa_input[:2] == "aʊ":
            ipa_input = ipa_input[2:]
            output_string += "W"
            continue
        if ipa_input[:2] == "dʒ":
            ipa_input = ipa_input[2:]
            output_string += "y"
            continue

    # do all the one-character runes
    if ipa_input[0] == "u":
        ipa_input = ipa_input[1:]
        output_string += "U"
        continue
    if ipa_input[0] == "æ":
        ipa_input = ipa_input[1:]
        output_string += "a"
        continue
    if ipa_input[0] == "ɑ":
        ipa_input = ipa_input[1:]
        output_string += "G"
        continue
    if ipa_input[0] == "i":
        ipa_input = ipa_input[1:]
        output_string += "F"
        continue
    if ipa_input[0] == "ɛ":
        ipa_input = ipa_input[1:]
        output_string += "e"
        continue
    if ipa_input[0] == "ʊ":
        ipa_input = ipa_input[1:]
        output_string += "L"
        continue
    if ipa_input[0] == "ɝ":
        ipa_input = ipa_input[1:]
        output_string += "V"
        continue
    if ipa_input[0] == "ə":
        ipa_input = ipa_input[1:]
        output_string += "Z"
        continue
    if ipa_input[0] == "ɪ":
        ipa_input = ipa_input[1:]
        output_string += "i"
        continue
    if ipa_input[0] == "ŋ":
        ipa_input = ipa_input[1:]
        output_string += "N"
        continue
    if ipa_input[0] == "ʒ":
        ipa_input = ipa_input[1:]
        output_string += "H"
        continue
    if ipa_input[0] == "θ":
        ipa_input = ipa_input[1:]
        output_string += "T"
        continue
    if ipa_input[0] == "ʃ":
        ipa_input = ipa_input[1:]
        output_string += "S"
        continue
    if ipa_input[0] == "t":
        ipa_input = ipa_input[1:]
        output_string += "t"
        continue
    if ipa_input[0] == "w":
        ipa_input = ipa_input[1:]
        output_string += "w"
        continue
    if ipa_input[0] == "w":
        ipa_input = ipa_input[1:]
        output_string += "w"
        continue
    if ipa_input[0] == "s":
        ipa_input = ipa_input[1:]
        output_string += "s"
        continue
    if ipa_input[0] == "r" or ipa_input[0] == "ɹ":
        ipa_input = ipa_input[1:]
        output_string += "r"
        continue
    if ipa_input[0] == "k":
        ipa_input = ipa_input[1:]
        output_string += "k"
        continue
    if ipa_input[0] == "p":
        ipa_input = ipa_input[1:]
        output_string += "p"
        continue
    if ipa_input[0] == "f":
        ipa_input = ipa_input[1:]
        output_string += "f"
        continue
    if ipa_input[0] == "g":
        ipa_input = ipa_input[1:]
        output_string += "g"
        continue
    if ipa_input[0] == "d":
        ipa_input = ipa_input[1:]
        output_string += "d"
        continue
    if ipa_input[0] == "n":
        ipa_input = ipa_input[1:]
        output_string += "n"
        continue
    if ipa_input[0] == "m":
        ipa_input = ipa_input[1:]
        output_string += "m"
        continue
    if ipa_input[0] == "z":
        ipa_input = ipa_input[1:]
        output_string += "z"
        continue
    if ipa_input[0] == "j":
        ipa_input = ipa_input[1:]
        output_string += "j"
        continue
    if ipa_input[0] == "v":
        ipa_input = ipa_input[1:]
        output_string += "v"
        continue
    if ipa_input[0] == "ʧ":
        ipa_input = ipa_input[1:]
        output_string += "c"
        continue
    if ipa_input[0] == "h":
        ipa_input = ipa_input[1:]
        output_string += "h"
        continue
    if ipa_input[0] == "ð":
        ipa_input = ipa_input[1:]
        output_string += "M"
        continue
    if ipa_input[0] == "l":
        ipa_input = ipa_input[1:]
        output_string += "l"
        continue
    if ipa_input[0] == "b":
        ipa_input = ipa_input[1:]
        output_string += "b"
        continue

    raise ValueError("no valid conversion was found for the start of this string:", ipa_input)

print(output_string)
