package main

import "core:math/rand"



GetRandomSentenceIndex :: proc() -> int {
    return rand.int_range(0, len(sentence_collection))
}



sentence_collection: []StringSet = {
    {"This is a test string to test realistic lengths of sentences.", "Mis iz B test striN tU test rFZlistik leNkTs Zv sentZnsZz."},
    {"No ruin seeker! Don\'t take the last slice of pizza! It\'s mine!", "no rUZn sFkV! don tBk MZ las slIs Zv pFtsZ! its mIn!"},
    {"I hope this program is helping to improve your reading speed.", "I hop Mis program iz helpiN tU imprUv jR rediN spFd."},
    {"I\'m just four sentences in and my brain is already struggling...", "Im yZst fR sentZnsZz in and mI brBn iz RedF strZgZliN..."},
    {"Astigmatism makes it harder to drive.", "ZstigmZtizZm mBks it hGrdV tU drIv."},
    {"Oh mama mia, Luigi is drunk again!", "o mGmZ mFZ, lUFyF iz drZNk ZgBn!"},
    {"I hope that my unhinged sentences get drowned out by better ones.", "I hop Mat mI Znhinyd sentZnsZz get drWnd Wt bI betV wZnz."},
    {"Vintage Story is a great game. You should go play it!", "vintiy stRF iz B grBt gBm. jU SLd go plB it!"},
    {"Odin is an amazing programming language. You should use it!", "odZn iz an ZmBziN programiN laNgwZy. jU SLd jUs it!"},
    {"Linux is an awesome operating system. You should try it!", "linZks iz an GsZm GpVBtiN sistZm. jU SLd trI it!"},
    {"The TUNIC soundtrack is absolutely phenomenal...", "MZ tUnik sWntrak iz absZlUtlF fZnGmZnZl..."},
    {"Remember to check your posture!", "rFmembV tU cek jR pGscV!"},
    {"Ordered ordering of ordinary lord hoards.", "RdVd RdViN Zv RdZnEF lRd hRdz."},
    {"Hexagons are honestly overrated... triangles are where it\'s at!", "heksZgGns Gr GnZslF ovVrBtid... trIaNgZlz Gr hwE its at!"},
    {"A small price to pay for big taco.", "B smGl prIs tU pB fR big tGko."},
    {"If I could walk I would run.", "if I kLd wGk I wLd rZn."},
    {"What\'s that? I dunno...", "hwZts Mat? I dZno..."},
    {"That could\'ve been bad!", "Mat kLdZv bin bad!"},
    {"Without the presence of light, the bug explodes.", "wiMWt MZ prezZns Zv lIt, MZ bZg iksplodz."},
    {"Why are pencils numbered? Is it just arbitrary or the numbers mean anything?", "hwI Gr pensZlz nZmbVd? iz it yZst GrbZtrEF R MZ nZmbVz mFn enFTiN?"},
    {"It\'s easier to write these when you stop caring about making sense.", "its FzFV tU rIt MFz hwen jU stGp kEiN ZbWt mBkiN sens."},
    {"I wish I could airbend...", "I wiS I kLd Ebend..."},
    {"I got afflicted with the right-ring-finger-hurts-a-lot-for-no-reason disease.", "I gGt Zfliktid wiM MZ rIt-riN-fiNgV-hVts-B-lGt-fR-no-rFzZn dizFz."},
    {"If I did a backflip I would be like \"woah I just did a backflip\".", "if I did B bakflip I wLd bF lIk \"wo I yZst did B bakflip\"."},
    {"Thanks for watching! Remember to like and subscribe!", "TaNks fR wGciN! rFmembV tU lIk and sZbskrIb!"},
    {"It\'s quite late right now, and I should probably go to sleep.", "its kwIt lBt rIt nW, and I SLd prGbZblF go tU slFp."},
    {"Nah I\'ll stay up anyways to make more sentences.", "nG Il stB Zp enFwBz tU mBk mR sentZnsZz."},
    {"I should maybe take care of my reminders soon.", "I SLd mBbF tBk kE Zv mI rFmIndVz sUn."},
    {"My daily todo-list has yet to have been done.", "mI dBlF tUdU-list haz jet tU hav bin dZn."},
    {"What, you egg? He stabs him.", "hwZt, jU eg? hF stabz him."},
    {"Getting my launchpad to work with my DAW was a nightmare.", "getiN mI lGncpad tU wVk wiM mI dG wGz B nItmE."},
    {"Maybe I will get into music production. Who knows?", "mBbF I wil get intU mjUzik pVdZkSZn. hU noz?"},
    {"It\'s gonna take a good while until I move to Wayland.", "its gGnZ tBk B gLd hwIl Zntil I mUv tU wBlZnd."},
    {"Okay no, I REALLY need to start preparing for sleep soon..!", "okB no, I rFlF nFd tU stGrt pVpEiN fR slFp sUn..!"},
    {"I wish animating was less tedious... or I\'m just bad in general.", "I wiS anZmBtiNg wGz les tFdFZs... R Im yZst bad in yenVZl."},
    {"I wish that I was rich so that I could tip artists a gazillion moneys.", "I wiS Mat I wGz ric so Mat I kLd tip Grtists B gZziljZn mZnFz."},
    {"Oh wow, kapok trees give a lot of seeds! They are very renewable!", "o wW, kBpGk trFz giv B lGt Zv sFdz! MB Gr vEF rFnUZbZl!"},
    {"One two oatmeal. Kirby is a pink guy.", "wZn tU otmFl. kVbF iz B piNk gI."},
    {"Bye bye forty hours of fun.", "bI bI fRtF WVz Zv fZn."},
    {"Most of the data lost has now been rebuilt.", "mos Zv MZ datZ lGst haz nW bin rFbilt."},
    {"This world feels like a parallel universe of the original one.", "Mis wVld fFlz lIk B pEZlel jUnZvVs Zv MZ ViyZnZl wZn."},
    {"At least our elks are comfortable. Their house is the same as before.", "at lFst WV elks Gr kZmfVtZbZl. ME hWs iz MZ sBm az bFfR."},
    {"Greenhouses require an insane amount of glass.", "grFnhWsiz rFkwIV an insBn ZmWnt Zv glas."},
    {"Shocking: You need to know a lot of rules and laws to be able to drive a car.", "SGkiN: jU nFd tU no B lGt Zv rUlz and lGz tU bF BbZl tU drIv B kGr."},
    {"The migration to Arch Linux is more involved than I would have hoped for...", "MZ mIgrBSZn tU Grc linZks iz mR invGlvd Man I wLd hav hopt fR..."},
    {"I should continue with writing Cotton\'s logbook soon huh?", "I SLd kZntinjU wiM rItiN kGtZnz lGgbLk sUn hZ?"},
    {"Always look a thousand times in each direction before crossing the street!", "GlwBz lLk B TWzZn tImz in Fc dIrekSin bFfR krGsiN MZ strFt!"},
    {"Otters are superior to every other species. This is objective fact.", "GtVz Gr sUpirFV tU evVF ZMV spFSFz. Mis iz Zbyektiv fakt."},
    {"Dragons come in second in the species ranking though.", "dragZnz kZm in sekZnd in MZ spFSFz raNkiN Mo."},
    {"As of recent I have been pretty bad with doing my todo list.", "az Zv rFsZnt I hav bin pritF bad wiM dUiN mI tUdU list."},
    {"Listen to \"Insomnia - Marimba Duet\" on YouTube. It is so good!!", "lisZn tU \"insGmnFZ - mVimbZ djUet\" Gn jUtUb. it iz so gLd!!"},
    {"Even though it is a bad idea, I want to own and know how to play a marimba.", "Fvin Mo it iz B bad IdFZ, I wGnt tU on and no hW tU plB B mVimbZ."},
    {"I wish for more fish.", "I wiS fR mR fiS."},
    {"Okay, when I have a lot of time it isn\'t too bad coming up with sentences.", "okB, hwen I hav B lGt Zv tIm it izZn tU bad kZmiN Zp wiM sentZnsZz."},
    {"Hell yeah! The music track \"HyperRogue OST - Jungle\" is awesome!", "hel ja! MZ mjUzik trak \"hIpVrog oestF - yZNgZl\" iz GsZm!"},
    {"It would be amazing if Super Mario Galaxy Three is ever made.", "it wLd bF ZmBziN if sUpV mGrFo galZksF TrF iz evV mBd."},
    {"Damn, Pop-OS is way way more broken than what I\'m used to.", "dam, pGp-oes iz wB wB mR brokZn Man hwZt Im jUzd tU."},
    {"There\'s a reason I haven\'t upgraded to the new version in like half a years..", "MEz B rFzZn I havZn ZpgrBdid tU MZ njU vVHZn in lIk haf B jirz.."},
    {"The spiders walking on my heard are just an illusion.", "MZ spIdVz wGkiN Gn mI hVd Gr yZst an ilUHZn."},
    {"The age of Arch Linux is quickly approaching... maybe.", "MZ By Zv Grc linZks iz kwiklF ZprociN... mBbF."},
    {"Nuh uh! My frog is better! They can jump a hundred meters up in the air!", "nU Z! mI frGg iz betV! MB kan yZmp B hZndVd mFtVz Zp in MZ E!"},
    {"Compiling this program on Windows is such a pain in the ass.", "kZmpIliN Mis program Gn windoz iz sZc B pBn in MZ as."},
    {"Man, I really want to try the game Kerbal Space Program again...", "man, I rFlF wGnt tU trI MZ gBm kVbLl spBs program ZgBn..."},
    {"Jumping as a mode of transport works better with anti-gravity material.", "yZmpiN az B mod Zv transpRt wVks betV wiM antI-gravZtF mZtirFZl."},
    {"Screw it! I\'m playing Kerbal Space Program despite all my ongoing projects!", "skrU it! Im plBiN kVbLl spBs program dispIt Gl mI GngoiN prGyeks!"},
    {"Wow KSP is incredibly difficult...", "wW kB-es-pF iz inkredZblF difZkZlt..."},
    {"I wish that my body didn\'t require food.", "I wiS Mat mI bGdF didZn rFkwIV fUd."},
    {"Welp, she\'s stuck on the moon now. Gotta do another mission to get her back.", "welp, SFz stZk Gn MZ mUn nW. gGtZ dU ZnZMV miSZn tU get hV bak."},
    {"Good that I\'m in sandbox-mode so that I can actually save her more easily.", "gLd Mat Im in sandbGks-mod so Mat I kan akcUZlF sBv hV mR FzZlF."},
    {"I\'m making an overkill rocket to save her from the moon.", "Im mBkiN an ovVkil rGkZt tU sBv hV frZm MZ mUn."},
    {"The game \"Big Walk\" is really nice with friends... if they aren\'t assholes.", "MZ gBm \"big wGk\" iz rFlF nIs wiM frendz... if MB GrZnt asholz."},
    {"The sound design in \"Big Walk\" is extremely pleasant.", "MZ sWnd dizIn in \"big wGk\" iz ekstrFmlF plezZnt."},
    {"I hope that the vacation will help me write more of Cotton\'s lore.", "I hop Mat MZ vBkBSZn wil help mF rIt mR Zv kGtZnz lR."},
    {"Oops I haven\'t done any todo items today at all...", "Ups I havZn dZn enF tUdU ItZmz tZdB at Gl..."},
    {"I should probably start doing that now.", "I SLd prGbZblF stGrt dUiN Mat nW."},
    {"Am I minimizing regret? Maybe to some extent.", "am I minZmIziN rZgret? mBbF tU sZm ikstent."},
    {"\"You are what you eat\", they said. \"Okay\", said the cinder block.", "\"jU Gr hwZt jU Ft\", MB sed. \"okB\", sed MZ sindV blGk."},
    {"Oh my god I have so many dishes that I need to do...", "o mI gGd I hav so menF diSZz Mat I nFd tU dU..."},
    {"Time to do driving quizzes whilst showering to save time!", "tIm tU dU drIviN kwiziz wIlst SWViN tU sBv tIm!"},
    {"Nevermind it definitely didn\'t save any time...", "nevVmInd it defZnZtlF didZn sBv enF tIm..."},
    {"It\'s almost like this happens every time, but that I never learn from it.", "its Glmost lIk Mis hapZnz evVF tIm, bZt Mat I nevV lVn frZm it."},
    {"Looks like I found a good rocket science tutorial to help me not die!", "lLks lIk I fWnd B gLd rGkZt sIZns tUtRFZl tU help mF nGt dI!"},
    {"A very small amount of commas in the sentences I write, huh?", "B vEF smGl ZmWnt Zv kGmZz in MZ sentZnsZz I rIt, hZ?"},
    {"It\'s interesting seeing how much everyone\'s sentences differ in style.", "its intVZstiN sFiN hW mZc evrFwZnz sentZnsZz difV in stIl."},
    {"My sentences are clearly more bullshit and relevant to what I\'m doing.", "mI sentZnsZz Gr klirlF mR bLlSit and relZvZnt tU hwZt Im dUiN."},
    {"I also have a tendency to split up the same thought into different sentences.", "I Glso hav B tendZnsF tU split Zp MZ sBm TGt intU difVZnt sentZnsZz."},
    {"This makes it way more nonsensical when actually using the program.", "Mis mBks it wB mR nGnsensikZl hwen akcUZlF jUziN MZ program."},
    {"It\'s at least an easy way to get more sentences.", "its at lFst an FzF wB tU get mR sentZnsZz."},
    {"What is your favorite color?", "hwZt iz jR fBvVit kZlV?"},
    {"I just played the game \"Big Walk\" with my boyfriend, and we loved it!", "I yZst plBd MZ gBm \"big wGk\" wiM mI bxfrend, and wF lZvd it!"},
    {"Oops we unlocked the blue area before the green one...", "Ups wF ZnlGkt MZ blU EFZ bFfR MZ grFn wZn..."},
    {"Oh shit! A rat!", "o Sit! B rat!"},
    {"Oh shit! A hat!", "o Sit! B hat!"},
    {"The purple dragon glides to save the day.", "MZ pVpZl dragZn glIdz tU sBv MZ dB."},
    {"Well, the moon landing was a success, however I didn\'t do my todo items again...", "wel, MZ mUn landiN wGz B sZkses, hWevV I didZn dU mI tUdU ItZmz ZgBn..."},
    {"Next time: Landing on the wacky other planet orbiting Earth.", "neks tIm: landiN Gn MZ wakF ZMV planZt RbZtiN VT."},
    {"It has a very weird orbit so planning maneuvers is going to be hard.", "it haz B vEF wird RbZt so planiN mZnUvVz iz goin tU bF hGrd."},
    {"My submissions are basically a timeline of all my shenanigans.", "mI sZbmiSZnz Gr bBsiklF B tImlIn Zv Gl mI SZnanigZnz."},

    // taken from the TUNIC manual
    {"Lost? See page twenty-eight.", "lGst? sF pBy twenF-Bt."},
    {"Everything hurts way more when I\'m tired.", "evrFTiN hVts wB mR hwen Im tIVd."},
    {"Keep your eye on your stamina-points!", "kFp jR I Gn jR stamZnZ-pxnts!"},
    {"Face your adversaries!", "fBs jR advVsEFz!"},
    {"At the start of evasion you have invulnerability.", "at MZ stGrt Zv FvBHZn jU hav invZlnVZbilitF."},
    {"Cards can change its nature...", "kGrdz kan cBny its nBcV..."},
    {"You can do it!", "jU kan dU it!"},
    {"Where are the keys?", "hwE Gr MZ kFz?"},
    {"Let's go and visit the hero\'s grave!", "lets go and vizit MZ hYoz grBv!"},
    
    // Jerma quotes
    {"Giving aliens edibles is an act of war", "giviN BlFZnz edZbZlz iz an akt Zv wR"},
    {"When in doubt, radish it out!", "hwen in dWt, radiS it Wt!"},
    {"THERE IS BLOOD IN THE BOX!", "ME iz blZd in MZ bGks!"},
    {"If I put you in a meat grinder...", "if I pLt jU in B mFt grIndV..."},

    // quote by u/idonotlikethisrock
    {"You\'re just mad that my shiny bald head is brighter than your future.", "jUr yZst mad Mat mI SInF bGld hed iz brItV Man jR fjUcV."},

    
    // user submitted sentences
    
    // by: big papa
    // amount: 12
    {"My left foot is shaped like a United States state.", "mI left fLt iz SBpt lIk B jUnItid stBts stBt."},
    {"My doctor asked me to stop calling him with a surly sensual voice.", "mI dGktV askt mF tU stGp kGliN him wiM B sVlF senSZwZl vxs."},
    {"Smoked meat, call that my rug burn.", "smokt mFt, kGl Mat mI rZg bVn."},
    {"Fake horse spotted in downtown, officers on standby!", "fBk hRs spGtid in dWntWn, GfZsVz Gn standbI!"},
    {"I have impostor syndrome. I got to be my therapists least favorite patient.", "I hav impGstV sindrom. I gGt tU bF mI TEZpists lFst fBvVit pBSZnt."},
    {"Sometimes I wake up at night and listen to the insects speak.", "sZmtImz I wBk Zp at nIt and lisZn tU MZ insekts spFk."},
    {"Oh boy my male snake laid eggs!", "o bx mI mBl snBk lBd egz!"},
    {"Burger King foot lettuce.", "bVgV kiN fLt letZs."},
    {"This muffin is looking awfully like a hamster. Someone baked my hamster into a muffin.", "Mis mZfZn iz lLkiN GflF lIk B hamstV. sZmwZn bBkt mI hamstV intU B mZfZn."},
    {"I came home late and we had no ice cubes in the freezer.", "I kBm hom lBt and wF had no Is kjUbz in MZ frFzV."},
    {"What happens after we pass? is it blissful silence or will my wife be there?", "hwZt hapZnz aftV wF pas? iz it blisfZl sIlZns R wil mI wIf bF ME?"},
    {"Who ate the last century egg?", "hU Bt MZ las sencVF eg?"},

    // by: Albin
    // amount: 11
    {"Writing haikus is really not that hard.", "rItiN hIkUz iz rFlF nGt Mat hGrd."},
    {"Whatever you do, never bring a sword to a sword fight.", "hwZtevV jU dU, nevV briN B sRd tU B sRd fIt."},
    {"I think you need to stay at home more and meet less people.", "I TiNk jU nFd tU stB at hom mR and mFt les pFpZl."},
    {"Becoming an adult is realizing cheese is really expensive.", "bikZmiN an adZlt iz rFZlIziN cFz iz rFlF ikspensiv."},
    {"I\'ve been really getting into giving up lately.", "Iv bin rFlF getiN intU giviN Zp lBtlF."},
    {"Apparently there have never been any aquatic dinosaurs, only marine reptiles?", "ZpEZntlF ME hav nevV bin enF Zkwatik dInZsRz, onlF mVFn reptIlz?"},
    {"How many roads must a man walk down? Forty-two.", "hW menF rodz mZst B man wGk dWn? fRtF-tU."},
    {"You really don\'t need any other drink than water.", "jU rFlF don nFd enF ZMV driNk Man wGtV."},
    {"If I lived in a room without windows I think I would crumble to dust.", "if I lIvd in B rUm wiMWt windoz I TiNk I wLd krZmbZl tU dZst."},
    {"Sometimes I wonder if the crazy frog really was that crazy after all.", "sZmtImz I wZndV if MZ krBzF frGg rFlF wGz Mat krBzF aftV Gl."},
    {"Time waits for no one.", "tIm wBts fR no wZn."},

    // by: Sveta
    // amount: 6
    {"Oh, language practice? Try these on for size!", "o, laNgwZy praktZs? trI MFz Gn fR sIz!"}, // I know you probably didn't intend for this one to be used but hihihi
    {"Why will we whittle wet whistles when winter whips?", "hwI wil wF hwitZl wet hwisZlz hwen wintV hwips?"},
    {"Alliteration is my passion, but clearly not my strong suite.", "ZlitVBSZn iz mI paSZn, bZt klirlF nGt mI strGN swFt."},
    {"My favorite word I learned this week is Hidalgo.", "mI fBvVit wVd I lVnd Mis wFk iz hZdalgo."},
    {"I know why the caged bird sings.", "I no hwI MZ kByd bVd siNz."},
    {"It is impractical to joist while on giraffe, but what a show!", "it iz impraktZkZl tU yxst hwIl Gn yVaf, bZt hwZt B So!"},

    // by: dxxander
    // amount: 4
    {"Through the darkness of future's past,", "TrU MZ dGrknZs Zv fjUcVz past,"},
    {"The magician longs to see.", "MZ mZyiSZn lGNz tU sF."},
    {"One chants out between two worlds,", "wZn cants Wt bFtwFn tU wVldz,"},
    {"Fire, walk with me.", "fIV, wGk wiM mF."},

    // by: DonQuijote
    // amount: 43
    {"The thieving scholar who seeks the cross but does not understand.", "MZ TFviN skGlV hU sFks MZ krGs bZt dZz nGt ZndVstand."},
    {"These gifts are fake.", "MFz gifs Gr fBk."},
    {"They used to be alive.", "MB jUzd tU bF ZlIv."},
    {"This is the last of its kind.", "Mis iz MZ las Zv its kInd."},
    {"Fish, fish, fish... Fishing for fish.", "fiS, fiS, fiS... fiSiN fR fiS."},
    {"A sleeping guardian.", "B slFpiN gGrdFZn."},
    {"Be careful.", "bF kEfZl."},
    {"Yoga helps the soul.", "jogZ helps MZ sol."},
    {"There\'s a secret save?", "MEz B sFkrZt sBv?"},
    {"Pick at the bones of this land.", "pik at MZ bonz Zv Mis land."},
    {"Don\'t trust the miasma.", "don trZst MZ mIazmZ."},
    {"Do not lose will.", "dU nGt lUz wil."},
    {"Hit the weak spot.", "hit MZ wFk spGt."},
    {"Press \"A\" to do a barrel roll.", "pres \"B\" tU dU B barZl rol."},
    {"Bombs create more bombs.", "bGmz krFBt mR bGmz."},
    {"The cake is a lie.", "MZ kBk iz B lI."},
    {"Snake? Snake. Snake!", "snBk? snBk. snBk!"},
    {"Acquired a questagon.", "ZkwIVd B kwestZgGn."},
    {"Fight the gauntlet, attain the crown.", "fIt MZ gGntlZt, ZtBn MZ krWn."},
    {"I want to eat a potato with tomato and cheese.", "I wGnt tU Ft B pZtBto wiM tZmGto and cFz."},
    {"If a gun uses mana, is it a magical staff?", "if B gZn jUsZz mGnZ, iz it B mayikZl staf?"},
    {"Attain your corporeal self again.", "ZtBn jR kRpRFZl self ZgBn."},
    {"This is your sign. Play void stranger.", "Mis iz jR sIn. plB vxd strBnyV."},
    {"Where is the forty-sixth room?", "hwE iz MZ fRtF-siksT rUm?"},
    {"They must really be forging with fury.", "MB mZst rFlF bF fRyiN wiM fjLrF."},
    {"If you find yourself next to a stick, pick it up.", "if jU fInd jRself neks tU B stik, pik it Zp."},
    {"No slugcat! Don\'t eat that neuron!", "no slZgkat! don Ft Mat nLrGn!"},
    {"Higher beings, these words are for you alone.", "hIV bFiNz, MFz wVdz Gr fR jU Zlon."},
    {"A good defense is a great defense.", "B gLd difens iz B grBt difens."},
    {"Thank you weird merchant.", "TaNk jU wird mVcZnt."},
    {"This sign can\'t stop me because I can\'t read.", "Mis sIn kant stGp mF bikGz I kant red."},
    {"A key is no mere plaything.", "B kF iz no mir plBTiN."},
    {"Are fairies annoying you? Can you just never hit them? Just cast fireball.", "Gr fEFz ZnxiN jU? kan jU yZst nevV hit Mem? yZst kast fIVbGl."},
    {"Pray and allow the far shore\'s power through.", "prB and ZlW MZ fGr SRz pWV TrU."},
    {"Press x to doubt.", "pres eks tU dWt."},
    {"This is a huge breakthrough!", "Mis iz B hjUy brBkTrU!"},
    {"They used to call me the drift king.", "MB jUzd tU kGl mF MZ drift kiN."},
    {"If you can\'t figure it out, go to sleep.", "if jU kant figjV it Wt, go tU slFp."},
    {"Are we the bad guys?", "Gr wF MZ bad gIz?"},
    {"Windmills are my biggest enemy.", "windmilz Gr mI bigZst enZmF."},
    {"Ruin seeker, grab your lure for emotional support.", "rUZn sFkV, grab jR lLr fR FmoSZnZl sZpRt."},
    {"Don\'t break my pots!", "don brBk mI pGts!"},
    {"Spoiler, there might be a \"secret legend\".", "spxlV, ME mIt bF B \"sFkrZt leyZnd\"."},   

    // by: Quantodeluz
    // amount: 45
    {"Nothing that can\'t be solved with some G U N", "nZTiN Mat kant bF sGlvd wiM sZm yF jU en"},
    {"Fairy fairy, come and speak. Show the way to what I seek!", "fEF fEF, kZm and spFk. So MZ wB tU hwZt I sFk!"},
    {"The notes Mason! What do they mean!?", "MZ nots mBsZn! hwZt dU MB mFn!?"},
    {"Git gud.", "git gLd."},
    {"It\'s really quite simple.", "its rFlF kwIt simpZl."},
    {"Give us the last proof.", "giv Zs MZ las prUf."},
    {"Big robot with the power of napalm!", "big robGt wiM MZ pWV Zv nBpGm!"},
    {"What happened to the cute fox game!?", "hwZt hapZnd tU MZ kjUt fGks gBm!?"},
    {"Gemstones you find, Keys of great shine!", "yemstonz jU fInd, kFz Zv grBt SIn!"},
    {"The quest nears its end...", "MZ kwest nirz its end..."},
    {"\"I\'ll set you free!\" Oh, poor of them.", "\"Il set jU frF!\" o, pUr Zv Mem."},
    {"Oh, a customization room!", "o, B kZs.tZ.mIzB.SZn rUm!"},
    {"Look, I have a white tuft!", "lLk, I hav B hwIt tZft!"},
    {"What is this, some sort of outer wilds?", "hwZt iz Mis, sZm sRt Zv WtV wIldz?"},
    {"Behold, my opus magnum: water!", "bihold, mI opZs magnZm: wGtV!"},
    {"Oh, shiny gold!", "o, SInF gold!"},
    {"Oh! shiny orb!!", "o! SInF Rb!!"},
    {"Truth can still be found from those in the wrong.", "trUT kan stil bF fWnd frZm Moz in MZ rGN."},
    {"Just listen for what they have to say.", "yZst lisZn fR hwZt MB hav tU sB."},
    {"Don\'t hate the wrong one, hate the wrong.", "don hBt MZ rGN wZn, hBt MZ rGN."},
    {"The curse is lifted!", "MZ kVs iz liftZd!"},
    {"The Heir is here no more!", "MZ E iz hY no mR!"},
    {"This world has so many secrets to find...", "Mis wVld haz so menF sFkrZts tU fInd..."},
    {"I don\'t think we\'re done.", "I don TiNk wV dZn."},
    {"Time to get the corkboard!", "tIm tU get MZ kRkbRd!"},
    {"Seeker, we\'re so screwed.", "sFkV, wV so skrUd."},
    {"Hey! Give me back my book!", "hB! giv mF bak mI bLk!"},
    {"Time for some deciphering!", "tIm fR sZm dZsIfViN!"},
    {"The moonlight can show hidden things.", "MZ mUnlIt kan So hidZn TiNz."},
    {"Annealed visions of the future.", "ZnFld viHZnz Zv MZ fjUcV."},
    {"The fulcrum has shattered!", "MZ fLlkrZm haz SatVd!"},
    {"Begone, Seeker of Ruin.", "bZgGn, sFkV Zv rUZn."},
    {"Come, Seeker of Runes.", "kZm, sFkV Zv rUnz."},
    {"May you become the Hero this world needs.", "mB jU bikZm MZ hYo Mis wVld nFdz."},
    {"May the Holy Cross be your guide and means.", "mB MZ holF krGs bF jR gId and mFnz."},
    {"Yes Rico... kaboom.", "jes rFko... kZbUm."},
    {"What a suspiciously shaped wallstone!", "hwZt B sZspiSZslF SBpt wGlston!"},
    {"What a conveniently hidden entrance!", "hwZt B kZnvFnjZntlF hidZn entrZns!"},
    {"Hey, this wasn\'t here yesterday...", "hB, Mis wGzZnt hY jestVdB..."},
    {"Show me what you\'ve got!", "So mF hwZt jUv gGt!"},
    {"The old that is strong does not wither.", "MZ old Mat iz strGN dZz nGt wiMV."},
    {"Have you eaten?", "hav jU FtZn?"},
    {"Have you had water?", "hav jU had wGtV?"},
    {"Have you slept?", "hav jU slept?"},
    {"I hope you\'re doing fine.", "I hop jUr dUiN fIn."},

    // by: GrapeDragon
    // amount: 4
    {"I like your ears and tail!", "I lIk jR Yz and tBl!"},
    {"This stick does not work very well.", "Mis stik dZz nGt wVk vEF wel."},
    {"Erm, what the slorm?", "Em, hwZt MZ slRm?"},
    {"I have spent too much money on Spyro merchandise.", "I hav spent tU mZc mZnF Gn spIro mVcZndIz."},

    // by: small-piece-of-grass
    // amount: 9
    {"My battery is almost dead.", "mI batVF iz Glmost ded."},
    {"Can you believe it?", "kan jU bilFv it?"},
    {"I had a long day.", "I had B lGN dB."},
    {"I keep dreaming about summer camp.", "I kFp drFmiN ZbWt sZmV kamp."},
    {"Isn’t it curious sometimes?", "izZn it kjLrFZs sZmtImz?"},
    {"I’m not an idiot! Though I may be a fool...", "Im nGt an idFZt! Mo I mB bF B fUl..."},
    {"What do you think about often?", "hwZt dU jU TiNk ZbWt GfZn?"},
    {"Well, here we are, nothing we can do.", "wel, hY wF Gr, nZTiN wF kan dU."},
    {"Sometimes things look prettier as ruins!", "sZmtImz TiNz lLk pritFV az rUZnz!"},
}
